[package]
name = "errors"
version = "0.1.0"
edition = "2024"

[dependencies]
uniffi = { workspace = true, features = [ "cli" ] }

[build-dependencies]
uniffi = { workspace = true, features = [ "build" ] }

[features]
ffi-trace = ["uniffi/ffi-trace"]